semi: false
singleQuote: true
trailingComma: es5
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - '<THIRD_PARTY_MODULES>'
  - '^(pages|components|utils|test)/(.*)$'
  - '^[./]'
