version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_USER:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: postgres
      PGOPTIONS: '-c log_statement=all'
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
